export const countryPhoneCodes = [
  { code: "+1", country: "US/CA" },
  { code: "+91", country: "IN" },
  { code: "+44", country: "GB" },
  { code: "+61", country: "AU" },
  { code: "+81", country: "JP" },
  { code: "+49", country: "DE" },
  { code: "+33", country: "FR" },
  { code: "+86", country: "CN" },
  { code: "+7", country: "RU" },
  { code: "+39", country: "IT" },
  { code: "+34", country: "ES" },
  { code: "+55", country: "BR" },
  { code: "+62", country: "ID" },
  { code: "+234", country: "NG" },
  { code: "+63", country: "PH" },
  { code: "+27", country: "ZA" },
  { code: "+971", country: "AE" },
  { code: "+82", country: "KR" },
  { code: "+880", country: "BD" },
  { code: "+92", country: "PK" },
  { code: "+94", country: "LK" },
  { code: "+98", country: "IR" },
  { code: "+90", country: "TR" },
  { code: "+20", country: "EG" },
  { code: "+31", country: "NL" }
];
